# https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html
[workspace]
resolver = "2"

members = [
  "sandbox",
  "session1",
  "session2",
  "session3",
  "session4",
  "session5",
  "polars_sandbox",
  "polars1",
  "polars2",
  "polars3"
]

